# Generated by Django 5.2.7 on 2025-10-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowednumber',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
